on:
  workflow_dispatch

env:
  SABANA_ACCESS_TOKEN: ${{secrets.SABANA_ACCESS_TOKEN}}
  SABANA_ID_TOKEN: ${{secrets.SABANA_ID_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install sabana Python SDK
        run: |
          python -m pip install sabana
          python -c "import sabana; print(sabana.__version__)"
      - name: Test project
        run: |
          python ./tests/test_sha_test.py
